### ISSUE TITLE
Using svrx from API: fsevents.watch is not a function

### ISSUE THREAD

**Issue by imyzf** [svrxjs/svrx#126]
**Describe the bug**
Using svrx from API, it will throw an error. But no problem from CLI.

**To Reproduce**
```
const Svrx = require('@svrx/svrx')

const server = new Svrx()
server.start()
```

**Screenshots**
API:
![image](https://user-images.githubusercontent.com/8298849/67265827-48572380-f4e1-11e9-91d7-16c8d56aa8cc.png)

CLI:
![image](https://user-images.githubusercontent.com/8298849/67266115-f4007380-f4e1-11e9-8702-42ec4b63461a.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - node v11.6.0

**Comment by xuchaoying** [comment]
Cannot reproduce now, feel free to reopen the issue if there's still a problem

**Comment by xuchaoying** [comment]
This bug is macOS only.

`fsevents.watch` is a new func  in `fsevents@2`. And `svrx` depends on `chokidar@3`,  and `fsevents@2` is an optional dependency of  `chokidar@3`.

Unfortunately, `svrx` uses shrinkwrap to lock all dependencies, which will drop all optional dependencies. That means **`svrx` won't install `fsevents` at all**.

`chokidar` will check if `fsevents` exist before use, which will prevent 'not found fsevents error':

```js
let fsevents;
try {
  fsevents = require('fsevents');
} catch (error) {
  if (process.env.CHOKIDAR_PRINT_FSEVENTS_REQUIRE_ERROR) console.error(error);
}
```

However, if your project has `fsevents` as a dependency and is not a version of 2, errors like  'fsevents.watch is not a function' might occur.

The workaround is **add `fsevents@2` as a dependency in your own project**.
